services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-docker:local
    container_name: spring-boot-docker-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: test
