spring.application.name=spring-boot-docker


# Database Connection using your Project ID and Password
#spring.datasource.url=jdbc:postgresql://db.vosutyyfirytxbisusvh.supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true
spring.datasource.username=postgres.vosutyyfirytxbisusvh
spring.datasource.password=[PASSWORD]
spring.datasource.driver-class-name=org.postgresql.Driver
# JWT Auth (Safe to keep as is, it's a public URL)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://vosutyyfirytxbisusvh.supabase.co/auth/v1

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect