spring.application.name=spring-boot-docker

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-timeout=20000

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false